[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "datawave_cli"
version = "1.0.1"
dependencies = [
    "requests",
    "kubernetes",
    "pandas",
    "argparse",
    "pytest"
]


[project.scripts]
datawave = "datawave_cli.main:main"